/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reserva;

import javax.swing.*;

/**
 *
 * @author Daniel
 */
public class JFrameAgregar extends javax.swing.JFrame {
    GestionarReservas reserva;

    /**
     * Creates new form JFrameAgregar
     */
    public JFrameAgregar() {
        initComponents();
        reserva=new GestionarReservas();
        jCheckBoxSitioConQuincho.setEnabled(false);
        jComboBoxTipoCabaña.setEnabled(false);
        jTextFieldIdCabaña.setEnabled(false);
        jTextFieldIdSitio.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSalir = new javax.swing.JButton();
        jLabelReserva = new javax.swing.JLabel();
        jComboBoxReserva = new javax.swing.JComboBox<>();
        jLabelNombre = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jLabelPasajeros = new javax.swing.JLabel();
        jLabelNumeroDeNoches = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jLabelIdCabaña = new javax.swing.JLabel();
        jLabelIdSitio = new javax.swing.JLabel();
        jLabelTipoCabaña = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jTextFieldPasajeros = new javax.swing.JTextField();
        jTextFieldNumeroDeNoches = new javax.swing.JTextField();
        jTextFieldId = new javax.swing.JTextField();
        jTextFieldIdCabaña = new javax.swing.JTextField();
        jTextFieldIdSitio = new javax.swing.JTextField();
        jButtonIngresarReserva = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jLabelMensaje = new javax.swing.JLabel();
        jCheckBoxSitioConQuincho = new javax.swing.JCheckBox();
        jComboBoxTipoCabaña = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agregar Reserva");

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jLabelReserva.setText("Reserva");

        jComboBoxReserva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Cabaña", "Sitio" }));
        jComboBoxReserva.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxReservaItemStateChanged(evt);
            }
        });
        jComboBoxReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxReservaActionPerformed(evt);
            }
        });

        jLabelNombre.setText("Nombre");

        jLabelTelefono.setText("Telefono");

        jLabelPasajeros.setText("Pasajeros");

        jLabelNumeroDeNoches.setText("Numero de noches");

        jLabelId.setText("ID");

        jLabelIdCabaña.setText("ID Cabaña");

        jLabelIdSitio.setText("ID Sitio");

        jLabelTipoCabaña.setText("Tipo Cabaña");

        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });

        jButtonIngresarReserva.setText("Ingresar Reserva");
        jButtonIngresarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarReservaActionPerformed(evt);
            }
        });

        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        jCheckBoxSitioConQuincho.setText("¿Sitio con quincho?");
        jCheckBoxSitioConQuincho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSitioConQuinchoActionPerformed(evt);
            }
        });

        jComboBoxTipoCabaña.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Estandar", "Especial", "Premium" }));
        jComboBoxTipoCabaña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoCabañaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelId)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldId))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabelNumeroDeNoches)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNumeroDeNoches, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelIdSitio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldIdSitio, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCheckBoxSitioConQuincho))
                        .addContainerGap(65, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelReserva)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabelPasajeros)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldPasajeros))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabelTelefono)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelIdCabaña)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldIdCabaña, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTipoCabaña)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxTipoCabaña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonIngresarReserva)
                            .addComponent(jButtonLimpiar)
                            .addComponent(jButtonSalir))
                        .addGap(70, 70, 70))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabelMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelReserva)
                    .addComponent(jComboBoxReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonIngresarReserva))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelefono)
                    .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPasajeros)
                    .addComponent(jTextFieldPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSalir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelIdSitio, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldIdSitio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxSitioConQuincho))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNumeroDeNoches)
                            .addComponent(jTextFieldNumeroDeNoches, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelId)
                            .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelIdCabaña)
                            .addComponent(jTextFieldIdCabaña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTipoCabaña)
                            .addComponent(jComboBoxTipoCabaña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(jLabelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jComboBoxReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxReservaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBoxReservaActionPerformed

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jComboBoxReservaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxReservaItemStateChanged
        // TODO add your handling code here:
        jTextFieldId.setText("");
        jTextFieldIdCabaña.setEnabled(false);
        jTextFieldIdSitio.setEnabled(false);
        jTextFieldNombre.setText("");
        jTextFieldNumeroDeNoches.setText("");
        jTextFieldPasajeros.setText("");
        jTextFieldTelefono.setText("");
        jLabelMensaje.setText("");
        jComboBoxTipoCabaña.setEnabled(false);
        jCheckBoxSitioConQuincho.setEnabled(false);
        if (jComboBoxReserva.getSelectedItem().equals("Cabaña")) {
            jTextFieldIdSitio.setEnabled(false);
            jTextFieldId.setEnabled(true);
            jTextFieldIdCabaña.setEnabled(true);
            jTextFieldNombre.setEnabled(true);
            jTextFieldNumeroDeNoches.setEnabled(true);
            jTextFieldPasajeros.setEnabled(true);
            jTextFieldTelefono.setEnabled(true);
            jCheckBoxSitioConQuincho.setEnabled(false);
            jComboBoxTipoCabaña.setEnabled(true);
        }
        if (jComboBoxReserva.getSelectedItem().equals("Sitio")) {
            jTextFieldIdSitio.setEnabled(true);
            jTextFieldId.setEnabled(true);
            jTextFieldIdCabaña.setEnabled(false);
            jTextFieldNombre.setEnabled(true);
            jTextFieldNumeroDeNoches.setEnabled(true);
            jTextFieldPasajeros.setEnabled(true);
            jTextFieldTelefono.setEnabled(true);
            jCheckBoxSitioConQuincho.setEnabled(true);
            jComboBoxTipoCabaña.setEnabled(false);
        } 

    }//GEN-LAST:event_jComboBoxReservaItemStateChanged

    private void jComboBoxTipoCabañaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoCabañaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoCabañaActionPerformed

    private void jCheckBoxSitioConQuinchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSitioConQuinchoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxSitioConQuinchoActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        // TODO add your handling code here:
        jTextFieldId.setText("");
        jTextFieldIdCabaña.setText("");
        jTextFieldIdSitio.setText("");
        jTextFieldNombre.setText("");
        jTextFieldNumeroDeNoches.setText("");
        jTextFieldPasajeros.setText("");
        jTextFieldTelefono.setText("");
        jComboBoxReserva.setSelectedItem("Seleccione");
        jLabelMensaje.setText("");
        jComboBoxTipoCabaña.setSelectedItem("Seleccione");
        jCheckBoxSitioConQuincho.setSelected(false);
        jLabelMensaje.setText("Limpio");
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonIngresarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarReservaActionPerformed
        // TODO add your handling code here:
        String reserva;
        int id;
        String nombre;
        int telefono;
        int pasajeros;
        int numeroDeNoches;
        int idCabaña;
        String tipo;
        String idSitio;
        boolean conQuincho;
        reserva = jComboBoxReserva.getSelectedItem().toString();
        jLabelMensaje.setText("Ingresado");
        if (reserva.equals("Seleccione")) {
            jLabelMensaje.setText("Debe seleccionar una reserva");
            jComboBoxReserva.requestFocus();
            return;
        }
        id = Integer.parseInt(jTextFieldId.getText());
        nombre = jTextFieldNombre.getText();
        if(jTextFieldNombre.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"El nombre no debe ser vacio, ingrese nuevamente: ");
            jLabelMensaje.setText("Ingrese nuevamente el nombre.");
            jTextFieldNombre.requestFocus();
            return;
        }
        telefono = Integer.parseInt(jTextFieldTelefono.getText());
        if(jTextFieldTelefono.getText().isEmpty()||telefono<0){
            JOptionPane.showMessageDialog(null,"El telefono debe ser mayor o igual a cero, ingrese nuevamente:");
            jLabelMensaje.setText("Ingrese nuevamente el telefono.");
            jTextFieldTelefono.requestFocus();
            return;
        }
        pasajeros = Integer.parseInt(jTextFieldPasajeros.getText());
        if(jTextFieldPasajeros.getText().isEmpty()||pasajeros<1){
            JOptionPane.showMessageDialog(null,"El numero de pasajeros debe ser mayor o igual a 1, ingrese nuevamente:");
            jLabelMensaje.setText("Ingrese nuevamente el numero de pasajeros.");
            jTextFieldPasajeros.requestFocus();
        }
        numeroDeNoches = Integer.parseInt(jTextFieldNumeroDeNoches.getText());
        if(jTextFieldNumeroDeNoches.getText().isEmpty()||numeroDeNoches<1){
            JOptionPane.showMessageDialog(null,"El numero de noches debe ser mayor o igual a 1, ingrese nuevamente:");
            jLabelMensaje.setText("Ingrese nuevamente el numero de noches.");
            jTextFieldNumeroDeNoches.requestFocus();
        }
        if (reserva.equals("Cabaña")) {
            idCabaña = Integer.parseInt(jTextFieldIdCabaña.getText());
            tipo = (String) jComboBoxTipoCabaña.getSelectedItem();
            Cabaña cabaña = new Cabaña(idCabaña, tipo, id, nombre, telefono, pasajeros, numeroDeNoches);
            if (GestionarReservas.agregarReserva(cabaña)) {
                JOptionPane.showMessageDialog(null, "Se Agrego la cabaña", "Agregar reserva", JOptionPane.INFORMATION_MESSAGE);
                //Si no funciona probar con "this".
            } else {
                JOptionPane.showMessageDialog(null, "No se agrego la cabaña", "Agregar reserva", JOptionPane.ERROR_MESSAGE);
            }
        }
        if (reserva.equals("Sitio")) {
            idSitio = jTextFieldIdSitio.getText();
            if (jCheckBoxSitioConQuincho.isSelected()) {
                conQuincho = true;
            } else {
                conQuincho = false;
            }
            Sitio sitio = new Sitio(idSitio, conQuincho, id, nombre, telefono, pasajeros, numeroDeNoches);
            if (GestionarReservas.agregarReserva(sitio)) {
                JOptionPane.showMessageDialog(null, "Se agrego el sitio", "AgregarReserva", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "No se agrego el sitio", "Agregar reserva", JOptionPane.ERROR_MESSAGE);
            }
        }


    }//GEN-LAST:event_jButtonIngresarReservaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameAgregar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIngresarReserva;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JCheckBox jCheckBoxSitioConQuincho;
    private javax.swing.JComboBox<String> jComboBoxReserva;
    private javax.swing.JComboBox<String> jComboBoxTipoCabaña;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelIdCabaña;
    private javax.swing.JLabel jLabelIdSitio;
    private javax.swing.JLabel jLabelMensaje;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNumeroDeNoches;
    private javax.swing.JLabel jLabelPasajeros;
    private javax.swing.JLabel jLabelReserva;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelTipoCabaña;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldIdCabaña;
    private javax.swing.JTextField jTextFieldIdSitio;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNumeroDeNoches;
    private javax.swing.JTextField jTextFieldPasajeros;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
